apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicddemo-deployment
  spec:
   selector:
    matchLabels:
      app: cicddemo-project
  template:
    metadata:
      labels:
        app: cicddemo-project
    spec:
      containers:
      - name: cicddemo-project
        image: ramu215/cicddemo
        ports:
        - containerPort: 8080